# This is split between the emilator and dployment only since the deployment
# does not seem to override the plugin config file correctly when it is there.
FROM iron/go:dev as builder
WORKDIR /go/src/github.com/vapor-ware/synse-snmp-plugin
COPY . .
RUN make build


FROM iron/go
LABEL maintainer="vapor@vapor.io"

WORKDIR /plugin

COPY --from=builder /go/src/github.com/vapor-ware/synse-snmp-plugin/build/plugin ./plugin
COPY config.yml .

CMD ["./plugin"]
